### ISSUE TITLE
update to bootstrap 4.1

### ISSUE THREAD

**Issue by nteetor** [nteetor/yonder#60]
The update includes, 

#### general 

- [x] Added new custom range form control.
- [x] Added new .carousel-fade modifier to switch carousel from horizontal sliding to crossfade.
- [ ] Added new .dropdown-item-text for plaintext dropdown items.
- [ ] [Added new .flex-fill, .flex-grow-*, and .flex-shrink-* utilities.](http://getbootstrap.com/docs/4.1/utilities/flex/#grow-and-shrink)
- [x] [Added new .table-borderless variant for tables.](http://getbootstrap.com/docs/4.1/content/tables/#borderless-table)
- [x] [Added new .text-monospace utility.](http://getbootstrap.com/docs/4.1/utilities/text/#monospace)
- [x] Added new .text-body (default body color), .text-black-50 (50% opacity black), and .text-white-50 (50% opacity white) utilities.
- [x] [Added new .shadow-* utilities for quickly adding box-shadows.](https://getbootstrap.com/docs/4.1/utilities/shadows/)
- [x] Added ability to disable Popper’s positioning in dropdowns.
- [x] Updated our Theming docs to confirm you cannot use CSS variables in media queries (sorry folks!).
- [x] Fixed longstanding issue with Chrome rendering CSS columns incorrectly for cards.
- [x] Deprecated .text-hide—you’ll see a warning during compilation—as it’s a dated and undocumented feature.
- [x] Fixed up Dashboard and Offcanvas examples across Firefox and IE.
- [ ] Breadcrumbs can now use non-string values as dividers.

#### css

(note that these issue and pr numbers are under the bootstrap repo)

- [x] #22799: Add .table-borderless option.
- [x] #22958: Add carousel fade option.
- [ ] #22965: Add .dropdown-item-text to allow plaintext items in dropdown menu lists.
- [x] #24249: Add new responsive utilities, .w-auto and .h-auto.
- [x] #25197: Update .sr-only mixin and utility to remove clip-path that caused performance degradation. Matches changes to upstream H5BP.
- [x] #25248: Prevent word-wrap in progress bars.
- [x] #25333: Add ability to change .table-striped from odd or even via Sass variable.
- [x] #25356: Fix rounded corners on custom file in input group.
- [ ] #25385: Add .flex-fill utility class. This was previously in our source code, and is mentioned in our navs docs, but was mistakenly dropped at some point.
- [x] #25386: Use variables for white and black in theme-color-level function.
- [x] #25400: Add basic position to dropup/right/left and dropdown-menu-right.
- [x] #25414: Override .custom-select's width in .form-inline.
- [x] #25503: Replace Unicode character in _hover.scss.
- [x] #25532: Fix pagination buttons hover z-index.
- [x] #25561: Create a variable for label margin bottom.
- [x] #25564: Use $input-bg for $custom-select-bg.
- [x] #25600: Add custom range input.
- [x] #25641: Make use of prefers-reduced-motion media query.
- [x] #25645: Disable link functionality on disabled btn-link.
- [x] #25657: Add variable, $table-caption-color, for table caption element.
- [x] #25672: Replace "loose" HEX values with their respective variables.
- [x] #25691: Add variable to handle the change of a modal border-radius.
- [x] #25736: Fix incorrect class .custom-file-control to .custom-file-label.
- [x] #25758: Add box-shadow utilities.
- [x] #25806: Collapse with flex elements.
- [x] #25807: Allow customization of breadcrumb border radius.
- [x] #25848: Removed commented out and useless navbar-align mixin.
- [x] #26172: Add .text-monospace utility.
- [ ] #26168: Add new .flex-grow-* and .flex-shrink-* utilities.
- [x] #26169: Fix Chrome's rendering of .card-columns.
- [x] #26170: Additional text color utilities.
- [x] #26173: Deprecate .text-hide with `@warn` notice.
- [ ] #25581: Allow non-string content as breadcrumb divider.

#### JS

- [x] #24092: Allow to disable Popper.js style for dropdowns.
- [x] #25218: Fix carousel transition duration.
- [x] #25219: Update dropdown to allow referenceElement.
- [x] #25398: Update jQuery to v3.3.1.
- [x] #25662, #25834: Variable transition durations
- [x] #25670: Remove unused variable.
- [x] #25671: Consistent usage of $(document.body) instead of $('body').
- [x] #25896: Use transitionEnd in QUnit since we moved away from PhantomJS
- [x] #25403: Dropdown - Skip element disabled via attribute when using keyboard navigation

**Comment by nteetor** [comment]
The new flex utilities, dropdown item text, and breadcrumb dividers are intentionally left out.
